//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Components.Resources.LocalizedStrings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Components.Resources.LocalizedStrings.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BottomSheet {
            get {
                return ResourceManager.GetString("BottomSheet", resourceCulture);
            }
        }
        
        internal static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        internal static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        internal static string Sizes {
            get {
                return ResourceManager.GetString("Sizes", resourceCulture);
            }
        }
        
        internal static string ContextMenu {
            get {
                return ResourceManager.GetString("ContextMenu", resourceCulture);
            }
        }
        
        internal static string Pickers {
            get {
                return ResourceManager.GetString("Pickers", resourceCulture);
            }
        }
        
        internal static string Checkboxes {
            get {
                return ResourceManager.GetString("Checkboxes", resourceCulture);
            }
        }
        
        internal static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        internal static string SearchPage {
            get {
                return ResourceManager.GetString("SearchPage", resourceCulture);
            }
        }
        
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        internal static string ListItems {
            get {
                return ResourceManager.GetString("ListItems", resourceCulture);
            }
        }
        
        internal static string Chip {
            get {
                return ResourceManager.GetString("Chip", resourceCulture);
            }
        }
        
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        internal static string New_version {
            get {
                return ResourceManager.GetString("New_version", resourceCulture);
            }
        }
        
        internal static string New_version_message {
            get {
                return ResourceManager.GetString("New_version_message", resourceCulture);
            }
        }
        
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        internal static string SelectPerson {
            get {
                return ResourceManager.GetString("SelectPerson", resourceCulture);
            }
        }
        
        internal static string Context_Menu_SingleAction {
            get {
                return ResourceManager.GetString("Context_Menu_SingleAction", resourceCulture);
            }
        }
        
        internal static string Context_Menu_TwoActions {
            get {
                return ResourceManager.GetString("Context_Menu_TwoActions", resourceCulture);
            }
        }
        
        internal static string Context_Menu_Choices_Multiple {
            get {
                return ResourceManager.GetString("Context_Menu_Choices_Multiple", resourceCulture);
            }
        }
        
        internal static string Context_Menu_Choices_Single {
            get {
                return ResourceManager.GetString("Context_Menu_Choices_Single", resourceCulture);
            }
        }
        
        internal static string Context_Menu_GroupedActions {
            get {
                return ResourceManager.GetString("Context_Menu_GroupedActions", resourceCulture);
            }
        }
        
        internal static string Context_Menu_Grouped_Choices_Single {
            get {
                return ResourceManager.GetString("Context_Menu_Grouped_Choices_Single", resourceCulture);
            }
        }
        
        internal static string Context_Menu_LongPressWithAction {
            get {
                return ResourceManager.GetString("Context_Menu_LongPressWithAction", resourceCulture);
            }
        }
        
        internal static string Action_Format {
            get {
                return ResourceManager.GetString("Action_Format", resourceCulture);
            }
        }
        
        internal static string Group_Format {
            get {
                return ResourceManager.GetString("Group_Format", resourceCulture);
            }
        }
        
        internal static string SearchPage_PlaceholderText {
            get {
                return ResourceManager.GetString("SearchPage_PlaceholderText", resourceCulture);
            }
        }
        
        internal static string SearchPage_HintText {
            get {
                return ResourceManager.GetString("SearchPage_HintText", resourceCulture);
            }
        }
        
        internal static string SearchPage_NoResultText {
            get {
                return ResourceManager.GetString("SearchPage_NoResultText", resourceCulture);
            }
        }
        
        internal static string Option_Format {
            get {
                return ResourceManager.GetString("Option_Format", resourceCulture);
            }
        }
        
        internal static string BottomSheet_Open {
            get {
                return ResourceManager.GetString("BottomSheet_Open", resourceCulture);
            }
        }
        
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        internal static string PickColor {
            get {
                return ResourceManager.GetString("PickColor", resourceCulture);
            }
        }
        
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        internal static string SkeletonLoading {
            get {
                return ResourceManager.GetString("SkeletonLoading", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        internal static string BottomSheet_OpenWithToolbar {
            get {
                return ResourceManager.GetString("BottomSheet_OpenWithToolbar", resourceCulture);
            }
        }
        
        internal static string SizesAsVisualBoxes {
            get {
                return ResourceManager.GetString("SizesAsVisualBoxes", resourceCulture);
            }
        }
        
        internal static string SizesAsFontSize {
            get {
                return ResourceManager.GetString("SizesAsFontSize", resourceCulture);
            }
        }
        
        internal static string Alerting {
            get {
                return ResourceManager.GetString("Alerting", resourceCulture);
            }
        }
        
        internal static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
        
        internal static string ShowSystemMessage {
            get {
                return ResourceManager.GetString("ShowSystemMessage", resourceCulture);
            }
        }
        
        internal static string RemoveSystemMessage {
            get {
                return ResourceManager.GetString("RemoveSystemMessage", resourceCulture);
            }
        }
        
        internal static string RemoveSystemMessageAnimate {
            get {
                return ResourceManager.GetString("RemoveSystemMessageAnimate", resourceCulture);
            }
        }
        
        internal static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        internal static string ChooseInput {
            get {
                return ResourceManager.GetString("ChooseInput", resourceCulture);
            }
        }
        
        internal static string PickIcon {
            get {
                return ResourceManager.GetString("PickIcon", resourceCulture);
            }
        }
        
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        internal static string TextInput {
            get {
                return ResourceManager.GetString("TextInput", resourceCulture);
            }
        }
        
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        internal static string IconColor {
            get {
                return ResourceManager.GetString("IconColor", resourceCulture);
            }
        }
        
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        internal static string DisplayDialog {
            get {
                return ResourceManager.GetString("DisplayDialog", resourceCulture);
            }
        }
        
        internal static string DisplayTemporaryDialog {
            get {
                return ResourceManager.GetString("DisplayTemporaryDialog", resourceCulture);
            }
        }
        
        internal static string DisplayErrorDialog {
            get {
                return ResourceManager.GetString("DisplayErrorDialog", resourceCulture);
            }
        }
        
        internal static string DisplayDestructiveDialog {
            get {
                return ResourceManager.GetString("DisplayDestructiveDialog", resourceCulture);
            }
        }
        
        internal static string Dialog_FakeTitle {
            get {
                return ResourceManager.GetString("Dialog_FakeTitle", resourceCulture);
            }
        }
        
        internal static string Dialog_FakeDescription {
            get {
                return ResourceManager.GetString("Dialog_FakeDescription", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Dialog_TemporaryDescription {
            get {
                return ResourceManager.GetString("Dialog_TemporaryDescription", resourceCulture);
            }
        }
        
        internal static string Dialog_DestructiveDescription {
            get {
                return ResourceManager.GetString("Dialog_DestructiveDescription", resourceCulture);
            }
        }
        
        internal static string Destroy {
            get {
                return ResourceManager.GetString("Destroy", resourceCulture);
            }
        }
        
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        internal static string DisplayTwoDialogs {
            get {
                return ResourceManager.GetString("DisplayTwoDialogs", resourceCulture);
            }
        }
        
        internal static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        internal static string IsRunningHintText {
            get {
                return ResourceManager.GetString("IsRunningHintText", resourceCulture);
            }
        }
        
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        internal static string ActivityIndicator {
            get {
                return ResourceManager.GetString("ActivityIndicator", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string Animations {
            get {
                return ResourceManager.GetString("Animations", resourceCulture);
            }
        }
        
        internal static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        internal static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        internal static string Context_Menu_LongPressWithDestructiveAction {
            get {
                return ResourceManager.GetString("Context_Menu_LongPressWithDestructiveAction", resourceCulture);
            }
        }
        
        internal static string Context_Menu_Divider {
            get {
                return ResourceManager.GetString("Context_Menu_Divider", resourceCulture);
            }
        }
        
        internal static string SelectAllTextOnFocus {
            get {
                return ResourceManager.GetString("SelectAllTextOnFocus", resourceCulture);
            }
        }
        
        internal static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        internal static string Unfocus {
            get {
                return ResourceManager.GetString("Unfocus", resourceCulture);
            }
        }
        
        internal static string TextFields {
            get {
                return ResourceManager.GetString("TextFields", resourceCulture);
            }
        }
        
        internal static string AreYouSure_ {
            get {
                return ResourceManager.GetString("AreYouSure?", resourceCulture);
            }
        }
        
        internal static string ThisWillCloseBottomSheet {
            get {
                return ResourceManager.GetString("ThisWillCloseBottomSheet", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string BottomSheet_OpenNotClosableInteracting {
            get {
                return ResourceManager.GetString("BottomSheet_OpenNotClosableInteracting", resourceCulture);
            }
        }
        
        internal static string Context_Menu_LongPress_OneItemOneGroup {
            get {
                return ResourceManager.GetString("Context_Menu_LongPress_OneItemOneGroup", resourceCulture);
            }
        }
        
        internal static string DefaultStateViews {
            get {
                return ResourceManager.GetString("DefaultStateViews", resourceCulture);
            }
        }
        
        internal static string CustomStateViews {
            get {
                return ResourceManager.GetString("CustomStateViews", resourceCulture);
            }
        }
        
        internal static string NoItemsToChooseFrom {
            get {
                return ResourceManager.GetString("NoItemsToChooseFrom", resourceCulture);
            }
        }
        
        internal static string BarcodeScanning {
            get {
                return ResourceManager.GetString("BarcodeScanning", resourceCulture);
            }
        }
    }
}
