//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Components.Resources.LocalizedStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings_nb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings_nb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Components.Resources.LocalizedStrings.LocalizedStrings.nb", typeof(LocalizedStrings_nb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling {0}.
        /// </summary>
        internal static string Action_Format {
            get {
                return ResourceManager.GetString("Action_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitetsindikator.
        /// </summary>
        internal static string ActivityIndicator {
            get {
                return ResourceManager.GetString("ActivityIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til knapp.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varsling.
        /// </summary>
        internal static string Alerting {
            get {
                return ResourceManager.GetString("Alerting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakgrunn.
        /// </summary>
        internal static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bakgrunnsfarge.
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bursdag.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom sheet.
        /// </summary>
        internal static string BottomSheet {
            get {
                return ResourceManager.GetString("BottomSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åpne bottom sheet.
        /// </summary>
        internal static string BottomSheet_Open {
            get {
                return ResourceManager.GetString("BottomSheet_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åpne bottom sheet med toolbar.
        /// </summary>
        internal static string BottomSheet_OpenWithToolbar {
            get {
                return ResourceManager.GetString("BottomSheet_OpenWithToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox.
        /// </summary>
        internal static string Checkboxes {
            get {
                return ResourceManager.GetString("Checkboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chip.
        /// </summary>
        internal static string Chip {
            get {
                return ResourceManager.GetString("Chip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg input.
        /// </summary>
        internal static string ChooseInput {
            get {
                return ResourceManager.GetString("ChooseInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farge.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farger.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komponenter.
        /// </summary>
        internal static string Components {
            get {
                return ResourceManager.GetString("Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flervalg.
        /// </summary>
        internal static string Context_Menu_Choices_Multiple {
            get {
                return ResourceManager.GetString("Context_Menu_Choices_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valgbare handlinger, kun et valg.
        /// </summary>
        internal static string Context_Menu_Choices_Single {
            get {
                return ResourceManager.GetString("Context_Menu_Choices_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupperte enkeltvalg.
        /// </summary>
        internal static string Context_Menu_Grouped_Choices_Single {
            get {
                return ResourceManager.GetString("Context_Menu_Grouped_Choices_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupperte handlinger.
        /// </summary>
        internal static string Context_Menu_GroupedActions {
            get {
                return ResourceManager.GetString("Context_Menu_GroupedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long press menu med en handling.
        /// </summary>
        internal static string Context_Menu_LongPressWithAction {
            get {
                return ResourceManager.GetString("Context_Menu_LongPressWithAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En handling med et ikon.
        /// </summary>
        internal static string Context_Menu_SingleAction {
            get {
                return ResourceManager.GetString("Context_Menu_SingleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To handlinger.
        /// </summary>
        internal static string Context_Menu_TwoActions {
            get {
                return ResourceManager.GetString("Context_Menu_TwoActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu.
        /// </summary>
        internal static string ContextMenu {
            get {
                return ResourceManager.GetString("ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall.
        /// </summary>
        internal static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ødelegg.
        /// </summary>
        internal static string Destroy {
            get {
                return ResourceManager.GetString("Destroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog.
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dette er en destruktiv dialog.
        /// </summary>
        internal static string Dialog_DestructiveDescription {
            get {
                return ResourceManager.GetString("Dialog_DestructiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En veldig lang beskrivelse.
        /// </summary>
        internal static string Dialog_FakeDescription {
            get {
                return ResourceManager.GetString("Dialog_FakeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test tittel.
        /// </summary>
        internal static string Dialog_FakeTitle {
            get {
                return ResourceManager.GetString("Dialog_FakeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne vil vare i 5 sekunder.
        /// </summary>
        internal static string Dialog_TemporaryDescription {
            get {
                return ResourceManager.GetString("Dialog_TemporaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis destruktiv dialog.
        /// </summary>
        internal static string DisplayDestructiveDialog {
            get {
                return ResourceManager.GetString("DisplayDestructiveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis dialog.
        /// </summary>
        internal static string DisplayDialog {
            get {
                return ResourceManager.GetString("DisplayDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis error dialog.
        /// </summary>
        internal static string DisplayErrorDialog {
            get {
                return ResourceManager.GetString("DisplayErrorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis midlertidig dialog.
        /// </summary>
        internal static string DisplayTemporaryDialog {
            get {
                return ResourceManager.GetString("DisplayTemporaryDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis to dialoger.
        /// </summary>
        internal static string DisplayTwoDialogs {
            get {
                return ResourceManager.GetString("DisplayTwoDialogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last ned.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varighet.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feil.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppe {0}.
        /// </summary>
        internal static string Group_Format {
            get {
                return ResourceManager.GetString("Group_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikon farge.
        /// </summary>
        internal static string IconColor {
            get {
                return ResourceManager.GetString("IconColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikoner.
        /// </summary>
        internal static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laster.
        /// </summary>
        internal static string IsRunning {
            get {
                return ResourceManager.GetString("IsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veksle på  om indikatoren skal laste.
        /// </summary>
        internal static string IsRunningHintText {
            get {
                return ResourceManager.GetString("IsRunningHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List items.
        /// </summary>
        internal static string ListItems {
            get {
                return ResourceManager.GetString("ListItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lasting.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigasjon.
        /// </summary>
        internal static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny versjon.
        /// </summary>
        internal static string New_version {
            get {
                return ResourceManager.GetString("New_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er en ny versjon tilgjengelig..
        /// </summary>
        internal static string New_version_message {
            get {
                return ResourceManager.GetString("New_version_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valg {0}.
        /// </summary>
        internal static string Option_Format {
            get {
                return ResourceManager.GetString("Option_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg farge.
        /// </summary>
        internal static string PickColor {
            get {
                return ResourceManager.GetString("PickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickers.
        /// </summary>
        internal static string Pickers {
            get {
                return ResourceManager.GetString("Pickers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg ikon.
        /// </summary>
        internal static string PickIcon {
            get {
                return ResourceManager.GetString("PickIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern alle.
        /// </summary>
        internal static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern System Melding.
        /// </summary>
        internal static string RemoveSystemMessage {
            get {
                return ResourceManager.GetString("RemoveSystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern System Melding Animert.
        /// </summary>
        internal static string RemoveSystemMessageAnimate {
            get {
                return ResourceManager.GetString("RemoveSystemMessageAnimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressurser.
        /// </summary>
        internal static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagring.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søkefelt.
        /// </summary>
        internal static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søking.
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søkeside.
        /// </summary>
        internal static string SearchPage {
            get {
                return ResourceManager.GetString("SearchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bruk søkefeltet for å søke etter folk..
        /// </summary>
        internal static string SearchPage_HintText {
            get {
                return ResourceManager.GetString("SearchPage_HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du fant ingen folk med søket ditt, vennligst prøv på nytt..
        /// </summary>
        internal static string SearchPage_NoResultText {
            get {
                return ResourceManager.GetString("SearchPage_NoResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk etter folk.
        /// </summary>
        internal static string SearchPage_PlaceholderText {
            get {
                return ResourceManager.GetString("SearchPage_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg person.
        /// </summary>
        internal static string SelectPerson {
            get {
                return ResourceManager.GetString("SelectPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis System Melding.
        /// </summary>
        internal static string ShowSystemMessage {
            get {
                return ResourceManager.GetString("ShowSystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Størrelse.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Størrelser.
        /// </summary>
        internal static string Sizes {
            get {
                return ResourceManager.GetString("Sizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Størrelser som font størrelse.
        /// </summary>
        internal static string SizesAsFontSize {
            get {
                return ResourceManager.GetString("SizesAsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Størrelser som bokser.
        /// </summary>
        internal static string SizesAsVisualBoxes {
            get {
                return ResourceManager.GetString("SizesAsVisualBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skeleton lasting.
        /// </summary>
        internal static string SkeletonLoading {
            get {
                return ResourceManager.GetString("SkeletonLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Meldinger.
        /// </summary>
        internal static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst farge.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst input.
        /// </summary>
        internal static string TextInput {
            get {
                return ResourceManager.GetString("TextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
    }
}
